import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Client } from "@notionhq/client";
import getConfig from "next/config";
import { postApis } from "../core/apis/posts";
import type { GetStaticPaths, GetStaticProps } from "next";
const inter = Inter({ subsets: ["latin"] });
export async function getStaticProps() {
  const res = await fetch("http://localhost:3001/api/posts");
  const data = await res.json();

  return {
    props: {
      data,
    },
    revalidate: 3600,
  };
}

const Home = ({ data }: any) => {
  console.log(data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Pages from Notion</h2>
      <div>
        {data?.data.map((item: any) => (
          <li key={item.id}>{item.id}</li>
        ))}
      </div>
    </>
  );
};

export default Home;
